export const CITIES = [
  "Ahmedabad",
  "All India",
  "Amaravati",
  "Ambur",
  "Ambur Tamil Nadu",
  "Anantapur",
  "Ananthapur",
  "Andhra Pradesh",
  "Aurangabad",
  "Ballari",
  "Bang",
  "Bangalore",
  "Bangalore He",
  "Banglore Karnataka",
  "Bareli",
  "Batlagundu",
  "Belgaum",
  "Bellary",
  "Bhopal",
  "Bidar",
  "Buldhana Mh",
  "Calicut",
  "Calicut Kerala",
  "Chennai",
  "Chikmanglor",
  "China",
  "Coimbatore",
  "Coorg",
  "Davangere",
  "Delhi",
  "Dharmapuri",
  "Dharwad",
  "Dindigul",
  "Dubai",
  "Ernakulam",
  "Erode",
  "Fujairah",
  "Goa",
  "Guargaon",
  "Gujrat",
  "Gulbarga",
  "Guntur",
  "Gurgao",
  "Gurgown",
  "Hariyar",
  "Hassan",
  "Haveri",
  "Hiriyur",
  "Hosur",
  "Hubbali",
  "Hubli",
  "Hyderabad",
  "Indore",
  "Jalna",
  "Jharkhand",
  "Ka",
  "Kadapa",
  "Kanpur",
  "Karnataka",
  "Kashmir",
  "Kerala",
  "Khammam",
  "Kolar",
  "Kolkata",
  "Kozhikode",
  "Kunigal",
  "Kurnool",
  "Lucknow",
  "Madurai",
  "Maharashtra",
  "Malappuram",
  "Manglore",
  "Meerut",
  "Mp",
  "Mumbai",
  "Mumbra Thane",
  "Muradabad",
  "Mysore",
  "Nagpur",
  "Nanded",
  "Nandyal Ap",
  "Nandyalap",
  "Nashik",
  "Nasik",
  "Navi Mumbai",
  "Ooty",
  "Panchmahal Up",
  "Patna",
  "Pavagada",
  "Pondicherry",
  "Pune",
  "Puzhal Chennai",
  "Qatar",
  "Raichur",
  "Rajasthan",
  "Ranipet Chennai",
  "Salem",
  "Sangli",
  "Shirpur",
  "Shrirampur",
  "Siddipet",
  "Sirsi",
  "Srinagar",
  "Tamil Nadu",
  "Telangana",
  "Thane",
  "Thanjavur",
  "Theni",
  "Tirupati",
  "Tiruppur",
  "Trichy",
  "Tripura",
  "Tumkur",
  "Tumkur District Karnataka",
  "Tumkur Karnataka",
  "Uttar Pradesh",
  "Vaniyambadi",
  "Velachery",
  "Vellore",
  "Vijayanagara",
  "Vijayapura",
  "Vijayawada",
  "Virudhunagar",
  "Visakhapatnam",
  "Vishakpatnam Ap"
];